name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Verify version matches tag
        run: |
          TOML_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          if [ "$TOML_VERSION" != "$TAG_VERSION" ]; then
            echo "Version in Cargo.toml ($TOML_VERSION) does not match git tag ($TAG_VERSION)"
            exit 1
          fi

      - name: Dry run
        run: cargo publish --dry-run

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
